# Generated by Django 5.2.4 on 2026-04-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_policydocument_trainingprogram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='material_file',
            field=models.FileField(blank=True, null=True, upload_to='training_materials/'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('vacation', 'Vacation'), ('study', 'Study'), ('special', 'Special'), ('compassionate', 'Compassionate'), ('sick', 'Sick'), ('maternity', 'Maternity'), ('away_on_business', 'Away on Business'), ('public_holiday', 'Public Holiday')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('forwarded', 'Forwarded to Management'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
