# Generated by Django 5.2.4 on 2026-04-09 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_weeklymenuitem_foodfeedback_foodorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodorder',
            options={'ordering': ['-week_start', 'weekday', '-ordered_at']},
        ),
        migrations.AddField(
            model_name='foodorder',
            name='requested_item',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='week_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='weekday',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.weeklymenuitem'),
        ),
    ]
