# Generated by Django 5.2.4 on 2026-04-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_foodorder_options_foodorder_requested_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklymenuitem',
            name='menu_image',
            field=models.ImageField(blank=True, null=True, upload_to='food_menus/'),
        ),
        migrations.AlterField(
            model_name='weeklymenuitem',
            name='item_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
