# Generated by Django 5.2.4 on 2026-04-15 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_weeklymenuitem_menu_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('1', 'Poor'), ('2', 'Fair'), ('3', 'Good'), ('4', 'Very Good'), ('5', 'Excellent')], default='3', max_length=1)),
                ('feedback_text', models.TextField(help_text='Your overall feedback on the training')),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations for upcoming trainings')),
                ('areas_for_elaboration', models.TextField(blank=True, help_text='Areas where the presenter should elaborate more')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employeeprofile')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='core.trainingprogram')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('training', 'submitted_by')},
            },
        ),
    ]
