# Generated by Django 5.2.4 on 2026-04-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_trainingfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='dependents_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='employment_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='pension_contribution_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='pension_policy_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='pension_provider',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
