# Generated by Django 5.2.4 on 2026-04-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_employeeprofile_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policydocument',
            name='category',
            field=models.CharField(choices=[('hr', 'HR Policies'), ('compliance', 'Compliance Policies')], default='hr', max_length=20),
        ),
    ]
