# Generated by Django 5.2.4 on 2026-05-06 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_employeeprofile_management_approver_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodorder',
            options={'ordering': ['-week_start', '-ordered_at']},
        ),
        migrations.AlterModelOptions(
            name='weeklymenuitem',
            options={'ordering': ['-week_start', 'item_name']},
        ),
        migrations.RemoveField(
            model_name='foodorder',
            name='weekday',
        ),
        migrations.RemoveField(
            model_name='weeklymenuitem',
            name='weekday',
        ),
        migrations.AddField(
            model_name='foodorder',
            name='week_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklymenuitem',
            name='week_end',
            field=models.DateField(default=datetime.datetime(2026, 5, 6, 13, 59, 51, 944722, tzinfo=datetime.timezone.utc), help_text='End date of the menu week (usually Friday or Sunday).'),
            preserve_default=False,
        ),
    ]
