# Generated by Django 5.2.14 on 2026-05-09 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_foodorder_options_alter_weeklymenuitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policydocument',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='core.company'),
        ),
    ]
