# Generated by Django 5.2.14 on 2026-05-09 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_policydocument_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayrollRecord',
        ),
    ]
