# Generated by Django 5.2.14 on 2026-05-09 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_delete_payrollrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodorder',
            options={'ordering': ['-week_start', 'order_day', '-ordered_at']},
        ),
        migrations.AddField(
            model_name='foodorder',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_orders', to='core.company'),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='order_day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], default='monday', help_text='Day to receive the food order', max_length=10),
        ),
        migrations.AddField(
            model_name='weeklymenuitem',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_menus', to='core.company'),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='requested_item',
            field=models.CharField(blank=True, default='', help_text='Type of food requested', max_length=150),
        ),
    ]
