# Generated by Django 5.2.14 on 2026-05-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_foodorder_options_foodorder_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='applicant_signature',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='applicant_signed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='authorized_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='authorized_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='authorized_signature',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_days_balance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='qualification_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='qualifies_for_leave',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='requested_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='total_leave_days_accrued',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='total_leave_days_taken',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
