# Generated by Django 5.2.14 on 2026-08-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_leaverequest_applicant_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='department',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
