# Generated by Django 5.2.14 on 2026-08-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_employeeprofile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='leave_days_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
