from django.urls import path
from django.contrib.auth.views import LogoutView

from .views import (
    FoodFeedbackPageView,
    FoodOrderPageView,
    FoodOrderUpdateView,
    FoodPortalView,
    EmployeeProfileCreateView,
    EmployeeProfileDeleteView,
    EmployeeProfileDetailView,
    EmployeeProfileListView,
    EmployeeProfileUpdateView,
    AppraisalDocumentCreateView,
    AppraisalDocumentDeleteView,
    AppraisalDocumentListView,
    AppraisalDocumentUpdateView,
    LeaveRequestCreateView,
    LeaveRequestDeleteView,
    LeaveRequestDecisionView,
    LeaveRequestListView,
    LeaveRequestUpdateView,
    PolicyDocumentCreateView,
    PolicyDocumentDeleteView,
    PolicyDocumentListView,
    PolicyDocumentUpdateView,
    RoleBasedLoginView,
    RoleRedirectView,
    TrainingFeedbackCreateView,
    TrainingFeedbackDeleteView,
    TrainingFeedbackDetailView,
    TrainingFeedbackListView,
    TrainingFeedbackUpdateView,
    download_training_feedback_detail,
    TrainingProgramCreateView,
    TrainingProgramDeleteView,
    TrainingProgramListView,
    TrainingProgramUpdateView,
    download_food_feedback_report,
    download_food_orders_report,
    download_training_feedback_report,
    download_leave_requests_report,
    download_leave_request_pdf,
    employee_dashboard,
    forward_leave_to_management,
    home,
    hr_dashboard,
    management_dashboard,
)

app_name = 'core'

urlpatterns = [
    path('', home, name='home'),
    path('login/', RoleBasedLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='core:login'), name='logout'),
    path('redirect/', RoleRedirectView.as_view(), name='redirect'),
    path('dashboard/employee/', employee_dashboard, name='employee-dashboard'),
    path('dashboard/hr/', hr_dashboard, name='hr-dashboard'),
    path('dashboard/management/', management_dashboard, name='management-dashboard'),
    path('profiles/', EmployeeProfileListView.as_view(), name='profile-list'),
    path('profiles/create/', EmployeeProfileCreateView.as_view(), name='profile-create'),
    path('profiles/<int:pk>/', EmployeeProfileDetailView.as_view(), name='profile-detail'),
    path('profiles/<int:pk>/edit/', EmployeeProfileUpdateView.as_view(), name='profile-edit'),
    path('profiles/<int:pk>/delete/', EmployeeProfileDeleteView.as_view(), name='profile-delete'),
    path('leave/', LeaveRequestListView.as_view(), name='leave-list'),
    path('leave/create/', LeaveRequestCreateView.as_view(), name='leave-create'),
    path('leave/<int:pk>/edit/', LeaveRequestUpdateView.as_view(), name='leave-edit'),
    path('leave/<int:pk>/delete/', LeaveRequestDeleteView.as_view(), name='leave-delete'),
    path('leave/<int:pk>/forward/', forward_leave_to_management, name='leave-forward'),
    path('leave/<int:pk>/review/', LeaveRequestDecisionView.as_view(), name='leave-review'),
    path('leave/<int:pk>/download/', download_leave_request_pdf, name='leave-download-pdf'),
    path('leave/report/', download_leave_requests_report, name='leave-report'),
    path('food/', FoodPortalView.as_view(), name='food-portal'),
    path('food/orders/', FoodOrderPageView.as_view(), name='food-orders-page'),
    path('food/feedback/', FoodFeedbackPageView.as_view(), name='food-feedback-page'),
    path('food/orders/<int:pk>/edit/', FoodOrderUpdateView.as_view(), name='food-order-edit'),
    path('food/orders/report/', download_food_orders_report, name='food-orders-report'),
    path('food/feedback/report/', download_food_feedback_report, name='food-feedback-report'),
    path('training/', TrainingProgramListView.as_view(), name='training-list'),
    path('training/create/', TrainingProgramCreateView.as_view(), name='training-create'),
    path('training/<int:pk>/edit/', TrainingProgramUpdateView.as_view(), name='training-edit'),
    path('training/<int:pk>/delete/', TrainingProgramDeleteView.as_view(), name='training-delete'),
    path('training-feedback/', TrainingFeedbackListView.as_view(), name='training-feedback-list'),
    path('training-feedback/create/', TrainingFeedbackCreateView.as_view(), name='training-feedback-create'),
    path('training-feedback/report/', download_training_feedback_report, name='training-feedback-report'),
    path('training-feedback/<int:pk>/download/', download_training_feedback_detail, name='training-feedback-download'),
    path('training-feedback/<int:pk>/', TrainingFeedbackDetailView.as_view(), name='training-feedback-detail'),
    path('training-feedback/<int:pk>/edit/', TrainingFeedbackUpdateView.as_view(), name='training-feedback-edit'),
    path('training-feedback/<int:pk>/delete/', TrainingFeedbackDeleteView.as_view(), name='training-feedback-delete'),
    path('appraisals/', AppraisalDocumentListView.as_view(), name='appraisal-list'),
    path('appraisals/create/', AppraisalDocumentCreateView.as_view(), name='appraisal-create'),
    path('appraisals/<int:pk>/edit/', AppraisalDocumentUpdateView.as_view(), name='appraisal-edit'),
    path('appraisals/<int:pk>/delete/', AppraisalDocumentDeleteView.as_view(), name='appraisal-delete'),
    path('policies/', PolicyDocumentListView.as_view(), name='policy-list'),
    path('policies/create/', PolicyDocumentCreateView.as_view(), name='policy-create'),
    path('policies/<int:pk>/edit/', PolicyDocumentUpdateView.as_view(), name='policy-edit'),
    path('policies/<int:pk>/delete/', PolicyDocumentDeleteView.as_view(), name='policy-delete'),
]
