services:

* type: web
  name: hr-portal
  runtime: python

  buildCommand: |
  pip install -r requirements.txt
  python manage.py collectstatic --noinput

  preDeployCommand: |
  python manage.py migrate

  startCommand: gunicorn config.wsgi:application --log-file -

  envVars:

  * key: SECRET_KEY
    generateValue: true

  * key: DEBUG
    value: "False"

  * key: ALLOWED_HOSTS
    value: ".onrender.com"

  * key: PYTHON_VERSION
    value: "3.11.9"

  * key: EMAIL_HOST
    value: "smtp.office365.com"

  * key: EMAIL_PORT
    value: "587"

  * key: EMAIL_USE_TLS
    value: "True"

  * key: EMAIL_HOST_USER
    value: "REPLACE_WITH_REAL_SENDING_ACCOUNT@intellego-ic.com"

  * key: DEFAULT_FROM_EMAIL
    value: "hr@intellego-ic.com"

  * key: PORTAL_BASE_URL
    value: "https://hr-portal-xguc.onrender.com/"

  * key: EMAIL_HOST_PASSWORD
    value: "REPLACE_WITH_REAL_SENDING_ACCOUNT_PASSWORD_OR_APP_PASSWORD"

databases:

* name: hr-portal-db
  databaseName: hr_portal
  user: hr_portal
